version: '3'

services:
    app:
        build:
            context: node
        container_name: app
        networks:
            - node-network
        volumes:
            - ./node:/app
            - /app/node_modules
        entrypoint: dockerize --wait tcp://db:3306 --timeout 20s docker-entrypoint.sh
        command: ["node", "index.js"]
        tty: true
        depends_on:
            - db
    db:
        image: mysql
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - node-network
    server:
        build:
            context: nginx
        container_name: server
        networks:
            - node-network
        tty: true
        ports:
            - "8080:80"
        depends_on:
            - app

networks:
    node-network:
        driver: bridge
